---
title: '.2 Plan design & data'
output:
  pdf_document: default
  html_document:
    df_print: paged
bibliography: ../../biblio.bib
---

# Instructions
Submit your answers to the seven first exercises through Campus Global. The remainder of your assignments concern self-studies.

# Describing a study
Kanwal et al. -@kanwal+etal:2017 taught subjects an artificial language with only three (made up) words: *zopudon*, *zopekil* and *zop*. The first two words refered to distinct objects (think: an apple for *zopudon* and a banana for *zopekil*). The short form *zop* could mean either. That is, *zop* is ambiguous, and thus can lead to misunderstandings. The core motivation for this study was to see if people would use the ambiguous word, *zop*, even though it is more risky than the unequivocal but longer alternatives *zopudon* and *zopekil* under certain experimental manipulations. Here's a glimpse of the data of the speakers:

```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
read_csv('senderdata.csv') %>%
  glimpse()
```


The column `pairnum` identifies each pair of subjects (one is the speaker, the other the receiver); the `IP` column identifies each subject; `trials` keep track of the order in which the trials happened; `display` codes whether one object (0/1) or another (2/3) was displayed to the subject; and `label` shows what the speaker actually said to communicate this object.

  1. What kind of study is this? Observational, experimental, or simulation?
  2. What kind of variable is `pairnum`? 
  3. What kind of variable is `trial`?
  4. What kind of variable is `label`?s
  
Inspect the sender data (`senderdata.csv') from Kanwal et al. yourself.

  5. How many times did the sender with `IP` $67.85.42.18$ say *zop*?
  6. How many unique pairs participated in the experiment? 
  7. How many sender trials did the experiment have for each subject?s
  8. Is this data *tidy*; *untidy* or *almost tidy*? 



# Self-study 
1. Work through Chapter 4 and 6 of [Introduction to Data Analysis](https://michael-franke.github.io/intro-data-analysis/Chap-02-01-data.html) [@aida]. If you need a refresher on descriptive statistics, also work through Chapter 5;
2. Apply the terminology from this session to your analysis question of interest. Change your research question if you have come across another that you find more interesting

# References