---
title: '4 Introduction to regression: Assignment'
output:
  pdf_document: default
  html_document:
    df_print: paged
bibliography: ../../biblio.bib
urlcolor: blue
---

# Instructions

Submit your answers to the 6 first exercises through Aula Global. 

# Regression

Consider the model `pitch ~ 1 + gender`, fit on the data from Franke & Roettger [-@franke+roettger:2019].

```{r}
df <- read.csv("https://tinyurl.com/polite-data") #download data

model <- lm(formula = pitch ~ 1 + gender, #fit model
            data = df)

#N.B.: this is equivalent to:
#model <- lm (df$pitch ~ 1 + df$gender)
```

  1. Is this model equivalent to `pitch ~ gender` or `pitch ~ gender + context`?
  2. Is `pitch` the outcome, a predictor, or neither?
  3. Is `gender` the outcome, a predictor, or neither?
  4. What is the predicted `pitch` of a `M`-gender speaker? Round your answer to the first decimal after the comma (if there are decimals)
  5. What is the predicted `pitch` of a `F`-gender speaker? Round your answer to the first decimal after the comma (if there are decimals) 
  6. What is the estimated difference between `M`- and `F`-gendered speakers? Round your answer to the first decimal after the comma (if there are decimals) 



# Self-study
Read  @winter:2013, pages 1-10: [https://arxiv.org/ftp/arxiv/papers/1308/1308.5499.pdf](https://arxiv.org/ftp/arxiv/papers/1308/1308.5499.pdf). If you find this interesting, read on until page 21. Pages 10-21 cover topics we will briefly touch on but will not be able to discuss in detail. If you're still interested, read the entire tutorial. The second part of the tutorial touches on a very powerful and useful extension of regression models that we won't cover in this class.

Use the remainder of your time to start working on your final report.
    
# References