---
title: 'Assignment'
output:
  pdf_document: default
  html_document:
    df_print: paged
urlcolor: blue
bibliography: ../../biblio.bib
---

# Self study

This week there is no practical exercise, and nothing to hand in. Use your time to work on your final report. Make sure you have all its details worked out by the end of the course.

We will cover some practical and theoretical data visualization in one of the upcoming sessions. However, since it is not the focus of this class but it is an incredibly interesting, useful, and new topic, I invite you to check out the following material if you're interested. If you are interested in practical data visualization using `ggplot2`, have a look at this tutorial: [https://uc-r.github.io/ggplot_intro](https://uc-r.github.io/ggplot_intro). If you are interested in the state of the art on what we know about effective data visualization, have a look at [Franconeri et al (2021): The Science of Visual Data Communication: What Works](https://www2.econ.iastate.edu/tesfatsi/ScienceOfVisualDataCommunication.FranconeriEtAl2021.pdf). 