---
title: 'Practical exercise (recuperación): Pronoun interpretation'
output:
  pdf_document: default
  html_document:
    df_print: paged
urlcolor: blue
bibliography: ../../biblio.bib
---

# Instructions

This is a *recuperación* for the practical exercise. You can do this exercise even if you passed the previous one. The highest grade will count. If you are already satisfied with the outcome of the first practical exercise, then don't hand in anything. Use the remainder of your time to work on your final report. Make sure you have all its details worked out by the end of the course.

As before, you will find a dataset prepared for you if you modify the **bolfaced** portion of the following link:

ADD_LINK

Each student has their own dataset, identified by their student ID. For instance, if your student ID is **u103672**, then your link is:

ADD_LINK

You can then load your data as
```{r}
df <- read.csv('replace_this_with_URL_to_your_data.csv')
```

The data is described below. Submit your answers to the questions as a PDF file, through Aula Global (upload task **in grup gran**). Round all answers to the second decimal after the comma.

# Data description

Variation in referential form, such the use of either a proper name (Peter) or a more reduced
pronominal expression (he), is an integral part of language use. The topic what exactly drives speakers' choices and listeners' interpretations to decide for one choice or interpretation over another is a long-standing and --to this date-- open debate. On the hearers' side, it is relatively uncontroversial that the boldfaced referent is more likely to be the intended referent of the pronoun in the sentence in (1) than in (2).

  1. **Sally** amazed Sara because she won the race.
  2. Sally amazed **Sara** because she won the race.

In other words, people generally take *she* to refer to the subject in this construction. 